### ISSUE TITLE
Broken link to example in the Wiki, under "Building your own Instrument"

### ISSUE THREAD

**Issue by Andy2No** [pschatzmann/Arduino-STK#16]
On the Wiki page for "Building your own Instrument", here:
https://github.com/pschatzmann/arduino-stk/wiki/Building-your-own-Instrument

there is a broken link to the example, towards the bottom of the page:

>Example

>An example can be found on Github

The link points to:
https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-stk/streams-stk_myinstrument-audiokit

which gives 404 - page not found.

I'm not clear where it should point.

**Comment by pschatzmann** [comment]
The STK examples are part of the DSP examples and can be found at https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-dsp/examples-stk
