### ISSUE TITLE
Broken links on the Instruments Wiki page

### ISSUE THREAD

**Issue by Andy2No** [pschatzmann/Arduino-STK#17]
On the Instruments Wiki page, near the top, the links to AudioKit and Voicer are broken:

>Instruments
Phil Schatzmann edited this page Sep 13, 2022 · 17 revisions

>I was testing the different Instruments on an AudioKit with the default sample rate proposed by STK. The Voicer can be used to output the sound of multiple instruments at the same time and it is using midi-notes (and not frequencies) as input.

**Comment by pschatzmann** [comment]
Can you provide a link ? 

I have no idea what you are referring to..
