### ISSUE TITLE
Debugging tools? 

### ISSUE THREAD

**Issue by jk367** [pschatzmann/arduino-stk#7]
Our Reseach group is having trouble getting sound output and we have no errors. Does this library have specialised debugging tools?

**Comment by pschatzmann** [comment]
The HelloSine.ino example shows how to output the generated data to Serial, so you can check if you get any audio.

As written in the Readme I recommend to use the [Arduino Audio Tools](https://github.com/pschatzmann/arduino-audio-tools) to do the real output. This will also help you to test the separate output possibilities separately (e.g. with the help of a sine wave).

If you use an ESP32 as output device e.g. with an external DAC, most likely you just  messed up with the pins! 
For giving any better advice I would need to know your hardware and what exactly you are doing that is not working.

The usual debugging tool would be an Oscilloscope where you would check the signal of your pins

**Comment by jk367** [comment]
Hi, we actually had the wiring wrong. We just needed to have the pin_ws connected to a different part of the esp-32.
